const menu = [
  {
    id: 1,
    title: "混色玫瑰小花束",
    category: "mix roses",
    price: 700,
    img: "../images/roses/rose-1.jpeg",
    desc: `1000元以下預算，最熱銷的款式。小巧精緻的包裝，足以打動你的心。`,
  },
  {
    id: 2,
    title: "赫本玫瑰",
    category: "red roses",
    price: 5500,
    img: "../images/roses/rose-2.jpeg",
    desc: `如同身著經典黑色晚禮服的奧黛麗赫本，簡單的服裝與頸上的珍珠項鍊，襯著唇上那一抹聚焦人心的玫瑰。我想將最經典的玫瑰花禮，贈送給心愛的女神。`,
  },
  {
    id: 3,
    title: "52赫茲",
    category: "blue roses",
    price: 1200,
    img: "../images/roses/rose-3.jpeg",
    desc: `海洋中最神秘與美麗的藍鯨，最特別的他留下那52赫的歌聲。慶幸自己在浩瀚的世界裡，找到理解我的你。`,
  },
  {
    id: 4,
    title: "雙子星（粉/藍玫瑰各一）",
    category: "pink roses",
    price: 2500,
    img: "../images/roses/rose-4.jpeg",
    desc: `11朵粉玫瑰花束與11朵藍玫瑰花束，閨蜜花束好選則！`,
  },
  {
    id: 5,
    title: "客製化粉色玫瑰花束",
    category: "pink roses",
    price: 2000,
    img: "../images/roses/rose-5.jpeg",
    desc: `20朵玫瑰花的花語是：「此情不渝，永遠愛你」。`,
  },
  {
    id: 6,
    title: "艾菈",
    category: "champange roses",
    price: 2100,
    img: "../images/roses/rose-6.jpg",
    desc: `Ella the name with the means of goddess,月亮女神艾菈美麗、堅強、勇敢的象徵。善良的她，每個夜裡選擇用微弱的光芒，輕輕的照在地球上。`,
  },
  {
    id: 7,
    title: "客製化粉色玫瑰花束",
    category: "pink roses",
    price: 2200,
    img: "../images/roses/rose-7.jpeg",
    desc: `閨蜜的人生大事，我想送他一份不一樣的禮物。要把我們的祝福、回憶、夢想、以及幸福全部包進去。`,
  },
  {
    id: 8,
    title: "11朵藍玫瑰花束",
    category: "blue roses",
    price: 1400,
    img: "../images/roses/rose-8.jpg",
    desc: `一心一意的愛、愛到一生一世。Love wholeheartedly, love forever.`,
  },
  {
    id: 9,
    title: "11朵紅玫瑰花束",
    category: "pink roses",
    price: 1200,
    img: "../images/roses/rose-9.jpeg",
    desc: `一心一意的愛、愛到一生一世。Love wholeheartedly, love forever.`,
  },
  {
    id: 10,
    title: "11朵藍玫瑰花束",
    category: "blue roses",
    price: 1400,
    img: "../images/roses/rose-10.jpg",
    desc: `一心一意的愛、愛到一生一世。Love wholeheartedly, love forever.`,
  },
  {
    id: 11,
    title: "赫本玫瑰",
    category: "red roses",
    price: 5500,
    img: "../images/roses/rose-11.jpeg",
    desc: `如同身著經典黑色晚禮服的奧黛麗赫本，簡單的服裝與頸上的珍珠項鍊，襯著唇上那一抹聚焦人心的玫瑰。我想將最經典的玫瑰花禮，贈送給心愛的女神。`,
  },
  {
    id: 12,
    title: "紅心皇后的花園 The Queen of Hearts Land",
    category: "red roses",
    price: 2200,
    img: "../images/roses/rose-12.jpeg",
    desc: `一不小心走入紅心皇后的花園並遇見了你，在這諾大的花園迷宮中，你就是我的出口。這辈子，都不離開你。`,
  },
  {
    id: 13,
    title: "深色系混色玫瑰花束",
    category: "mix roses",
    price: 2200,
    img: "../images/roses/rose-13.jpeg",
    desc: `粉玫瑰與紅玫瑰的結合，搭配滿天星與的點綴，黑色包裝象徵我們度過的夜晚，我把我們美好回憶裡的夜空，打包送你。`,
  },
  {
    id: 14,
    title: "11朵紅玫瑰花束",
    category: "red roses",
    price: 1200,
    img: "../images/roses/rose-14.jpeg",
    desc: `一心一意的愛、愛到一生一世。Love wholeheartedly, love forever.`,
  },
  {
    id: 15,
    title: "11朵紅玫瑰花束",
    category: "red roses",
    price: 1200,
    img: "../images/roses/rose-15.jpeg",
    desc: `一心一意的愛、愛到一生一世。Love wholeheartedly, love forever.`,
  },
  {
    id: 16,
    title: "紅玫瑰小香風包裝",
    category: "red roses",
    price: 2000,
    img: "../images/roses/rose-16.jpg",
    desc: `我想來一束，不用太大，足以裝滿我的心意，把思緒緊緊的包再一起的花。`,
  },
  {
    id: 17,
    title: "白玫瑰小香風包裝",
    category: "white roses",
    price: 2000,
    img: "../images/roses/rose-17.JPG",
    desc: `我想來一束，不用太大，足以裝滿我的心意，把思緒緊緊的包再一起的花。`,
  },
  {
    id: 18,
    title: "淺色系混色玫瑰花束",
    category: "mix roses",
    price: 2200,
    img: "../images/roses/rose-18.jpeg",
    desc: `粉玫瑰與紅玫瑰的結合，搭配滿天星與桔梗的點綴，最後用上米白色包裝作為襯托，在炎熱的盛夏，我想帶給你一絲清爽。`,
  },
  {
    id: 19,
    title: "第二顆鈕扣 The SECOND button",
    category: "pink roses",
    price: 1400,
    img: "../images/roses/rose-19.JPG",
    desc: `cute as a button就像小小的鈕扣一樣可愛。 最靠近心的第二顆鈕扣，是留給最特別的人。`,
  },
  {
    id: 20,
    title: "赤誠",
    category: "red roses",
    price: 3800,
    img: "../images/roses/rose-20.jpeg",
    desc: `You had me at hello 見到你得第一眼，我的心就被奪走了，鮮紅的玫瑰代表著我裸露的真心與誠意。`,
  },
  {
    id: 21,
    title: "藍天中的白雲",
    category: "white roses",
    price: 1200,
    img: "../images/roses/rose-21.png",
    desc: `一心一意的愛、愛到一生一世。Love wholeheartedly, love forever.`,
  },
  {
    id: 22,
    title: "盛夏羣星 Midsummer Stars",
    category: "white roses",
    price: 2500,
    img: "../images/roses/rose-22.png",
    desc: `把我們夏天最美的回憶,包裝起來送給你。`,
  },
  {
    id: 23,
    title: "11朵香檳玫瑰花束",
    category: "champange roses",
    price: 1200,
    img: "../images/roses/rose-23.png",
    desc: `一心一意的愛、愛到一生一世。Love wholeheartedly, love forever.`,
  },
  {
    id: 24,
    title: "客製化紅玫瑰花束",
    category: "red roses",
    price: 1500,
    img: "../images/roses/rose-24.png",
    desc: `牛皮紙的包裝，是把我們牽起來的契機。我想訂製這束花，把當年的信封、紙與墨，透過花朵，再一次呈現在你面前。`,
  },
];
export default menu;
